### ISSUE TITLE
画像サムネイルのサイズ変更機能および表示数の変更機能

### ISSUE THREAD

**Issue by minagiduki** [tizerm/Mistdon#23]
カラム数が少ないor横幅が大きいと(チャットレイアウトだとしても)画像が大きくなりすぎてしまう為、
「サムネイルの最大サイズ(px)」を指定して横に並ぶ数を自由に決められるようにして、
おまけとしてホームレイアウト時もデフォルトで5枚以上表示できるようにしてほしいです。
(製作者さんしかIssue書いてないけどここに書いて大丈夫だったでしょうか…？)

**Comment by tizerm** [comment]
@minagiduki ご意見ありがとうございます！
どうするかについては後ほど決めますが、とりあえずご意見として参考にさせていただきます。

**Comment by tizerm** [comment]
https://github.com/tizerm/Mistdon/pull/20/commits/6a9f9482dd251f0a2b7a83efb684c6f7d3581684
とりあえずこのコミットで部分的に対応しました。v0.5.1でリリース予定です。
ノーマルは240px、チャットは160px、メディアは320px以上の高さにはなりません。
最大サイズをユーザーで決められるようにするのは全体設定を入れる予定のv1.0.0以降になると思いますのでとりあえず一旦これでガマンしてくれ……。

**Comment by tizerm** [comment]
PullRequest #20 で機能をリリースしました！
暫定対応ということでIssueはとりあえず開けっ放しにします。

**Comment by tizerm** [comment]
v1.0.0(#29 )で縦の最大サイズを設定できるようにしたのでこちらはクローズさせていただきます！
ありがとうございました！
