### ISSUE TITLE
[v0.5.1]ヘルプ内誤植

### ISSUE THREAD

**Issue by yuni-tsuki** [tizerm/Mistdon#41]
# 概要
ヘルプ内の上部目次に「v0.4.1で実装されていない基本機能について」という項目がありますが、本文内の見出しでは「v0.5.1で実装されていない基本機能について」となっています。誤植と考えられますので、対応よろしくお願いします
![mistdon_bug_image](https://github.com/tizerm/Mistdon/assets/84435041/eb2c1fc0-9d4b-4069-a7ad-e426dccf216d)

**Comment by tizerm** [comment]
ご報告ありがとうございます！
当該項目はv1.0.0リリース時に削除されるのでv1.0.0で対応されます！
あともう少しなのでお待ち下さい！

**Comment by yuni-tsuki** [comment]
ありがとうございます。正式リリースをお待ちしております！
