### ISSUE TITLE
ドメイン名の末尾にスラッシュが付いた状態で認証できてしまう

### ISSUE THREAD

**Issue by hanubeki** [tizerm/Mistdon#62]
#61 で修正された読み込み不良の不具合に関して少し調べたところ、認証しているアカウントの一部にてドメイン名の末尾にスラッシュが付いていることに気づきました。
そこでMistdonの設定ファイルを覗いてみたところ、カスタム絵文字キャッシュ関連のファイル構造が以下のようになっていました。

```
app_prefs
├ emojis
│├ fedibird.com
││└ .json
│└ social.vivaldi.net.json
├ auth.json
├ columns.json
├ emoji_history.json
├ general_pref.json
└ history.json
```

ドメイン名の末尾にスラッシュが付いていたことによりカスタム絵文字キャッシュのディレクトリ構造に異常が生じ、正しく認識されず、v1.2.1での読み込み不良につながったと考えます。

**Comment by tizerm** [comment]
ご報告ありがとうございます！
現象は理解したので具体的な対応は後ほど考えます。

**Comment by tizerm** [comment]
Pull Request #66  でv1.3.0をリリースしたのでクローズします！ありがとうございました！
